import dns from 'dns';
import { Client } from 'ssh2';

const domain = 'cdn.node-ping-stat.ru';
const targetCname = '905f6c53ed0d0bf9.topology.gslb.yccdn.ru';

const sshConfig = {
  host: '141.11.197.6',
  port: 22,
  username: 'root',
  password: 'IxJlIDug5LW5mF5ghOts'
};

console.log('====================================================');
console.log('🔄 RESUMING CDN BYPASS SETUP...');
console.log('====================================================');
console.log(`Step 1: Checking DNS record for ${domain}...`);

dns.resolveCname(domain, (err, addresses) => {
  if (err || !addresses.includes(targetCname)) {
    console.log(`\n❌ DNS is NOT ready yet.`);
    if (err) {
      console.log(`   Detail: CNAME query returned error: ${err.message}`);
    } else {
      console.log(`   Detail: CNAME points to other target: ${addresses.join(', ')}`);
    }
    console.log('\n👉 WHAT TO DO NEXT:');
    console.log('   Please wait a few more minutes and run this script again:');
    console.log('   node scratch/resume-setup.js\n');
    process.exit(0);
  }

  console.log(`\n✅ DNS is successfully configured and pointing to Yandex CDN!`);
  console.log(`Step 2: Connecting to VPS to activate bypass configuration...`);

  const conn = new Client();
  
  function executeCommand(conn, cmd) {
    return new Promise((resolve, reject) => {
      conn.exec(cmd, (err, stream) => {
        if (err) return reject(err);
        let stdout = '';
        let stderr = '';
        stream.on('close', (code) => {
          resolve({ code, stdout, stderr });
        }).on('data', (data) => {
          stdout += data.toString();
        }).stderr.on('data', (data) => {
          stderr += data.toString();
        });
      });
    });
  }

  conn.on('ready', async () => {
    console.log('✅ SSH Connection established with VPS.');
    try {
      const envPath = '/root/knight-vpn-bot/.env';
      console.log(`Step 3: Modifying ${envPath} to enable CDN bypass...`);
      
      // Update .env settings
      await executeCommand(conn, `sed -i 's/USE_CDN_BYPASS=false/USE_CDN_BYPASS=true/g' ${envPath}`);
      await executeCommand(conn, `sed -i 's/CDN_DOMAIN=.*/CDN_DOMAIN=cdn.node-ping-stat.ru/g' ${envPath}`);
      
      console.log('Step 4: Restarting Knight VPN Bot...');
      await executeCommand(conn, "pm2 restart knight-vpn-bot");
      
      console.log('\n🎉 SUCCESS: CDN Bypass is now ACTIVE! 🎉');
      console.log('   All subscription links generated by the bot will now use the CDN-based profile.');
      console.log('   Test your subscription link in Hiddify or Happ to verify.');
      console.log('====================================================');
      conn.end();
    } catch (err) {
      console.error('❌ Error during VPS configuration:', err.message);
      conn.end();
    }
  }).on('error', (err) => {
    console.error('❌ SSH Connection failed:', err.message);
  }).connect(sshConfig);
});
